# Interval for checking the wan ip address in seconds
interval = 10
# Webservice that returns the wan_ip of the requesting client in plaintext format
ip_webservice = "https://checkip.amazonaws.com"

# List of services to update

# [[services]]

# [services.dyndns2]
# server = "dyndns.example.com"
# identifier = "example.com"
# password = "supersecurepassword"
# login = "myaccount"
